--  CASCADE
DROP TABLE IF EXISTS dates CASCADE;
CREATE TABLE dates (
  id SERIAL PRIMARY KEY NOT NULL,
  start_date TIMESTAMPTZ,
  end_date TIMESTAMPTZ,
  allDay BOOLEAN DEFAULT FALSE,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE
);
