--  CASCADE
DROP TABLE IF EXISTS dates CASCADE;
CREATE TABLE dates (
  id SERIAL PRIMARY KEY NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  event_id INTEGER REFERENCES events(id) ON DELETE CASCADE
);
