DROP TABLE IF EXISTS votes CASCADE;
CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCE users(id) ON DELETE CASCADE,
  event_id INTEGER REFERENCE events(id) ON DELETE CASCADE,
  date_id INTEGER REFERENCE dates(id) ON DELETE CASCADE,
  yes_no BOOLEAN
);
